# Generated by Django 5.1.3 on 2024-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique Identifier')),
            ],
        ),
    ]
