# Generated by Django 5.1.3 on 2024-12-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique Identifier')),
                ('file_name', models.CharField(max_length=50, unique=True, verbose_name='CSV File Name')),
                ('orig_csv_file', models.FileField(null=True, upload_to='visitors/csv_files/original', verbose_name='Original CSV FILE')),
                ('clean_csv_file', models.FileField(blank=True, null=True, upload_to='visitors/csv_files/clean', verbose_name='Cleaned CSV FILE')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-updated_at'],
            },
        ),
    ]
