# Generated by Django 5.1.3 on 2024-12-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportGeneratorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='file_name',
            field=models.CharField(max_length=50, verbose_name='CSV File Name'),
        ),
    ]
