# Generated by Django 5.1.3 on 2024-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportGeneratorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='clean_csv_file',
            field=models.FileField(null=True, upload_to='visitors/csv_files/clean', verbose_name='Cleaned CSV FILE'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='orig_csv_file',
            field=models.FileField(null=True, upload_to='visitors/csv_files/original', verbose_name='Original CSV FILE'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique Identifier'),
        ),
    ]
