# Generated by Django 5.1.3 on 2024-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportGeneratorApp', '0002_visitors_clean_csv_file_visitors_orig_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='file_name',
            field=models.CharField(default='tested.csv', max_length=50, unique=True, verbose_name='CSV File Name'),
            preserve_default=False,
        ),
    ]
